#!/usr/bin/env python3
"""Verify a hard OP deck where the ordinary path fails and PTA converges."""

from __future__ import annotations

import argparse
import math
import re
import subprocess
import sys
import tempfile
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from compare_spice import parse_listing  # noqa: E402


METRIC_RE = re.compile(
    r"^\s*(normalized_derivative|normalized_dc_residual):\s*(\S+)\s*$",
    re.MULTILINE,
)
PTA_OPTIONS = (
    "--pta-option",
    "initial-step=1",
    "--pta-option",
    "maximum-step=1k",
    "--pta-option",
    "maximum-steps=20000",
    "--pta-option",
    "derivative-tolerance=1e-3",
    "--pta-option",
    "dc-residual-tolerance=1e-3",
)
ABSOLUTE_TOLERANCE = {
    "v(vdd)": 1.0e-6,
    "v(q)": 1.0e-5,
    "v(qb)": 1.0e-8,
    "i(vdd)": 1.0e-10,
}


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("simulator", type=Path)
    parser.add_argument("netlist", type=Path)
    parser.add_argument("reference", type=Path)
    return parser.parse_args()


def run(simulator: Path, *arguments: object) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            [str(simulator), *map(str, arguments)],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
            timeout=30,
        )
    except subprocess.TimeoutExpired as error:
        raise RuntimeError(f"simulator timed out: {error.cmd}") from error


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def check_pta_diagnostics(stderr: str) -> None:
    require("PTA diagnostics:" in stderr, "PTA diagnostics are missing")
    require("converged: true" in stderr, "PTA did not report convergence")
    require(
        "status: PTA was not invoked" not in stderr,
        "fallback returned without invoking PTA",
    )

    metrics = {name: float(value) for name, value in METRIC_RE.findall(stderr)}
    require(
        set(metrics) == {"normalized_derivative", "normalized_dc_residual"},
        f"incomplete PTA convergence metrics: {metrics}",
    )
    require(
        all(math.isfinite(value) and 0.0 <= value < 1.0e-3
            for value in metrics.values()),
        f"invalid or unconverged PTA metrics: {metrics}",
    )


def check_operating_point(listing: Path, reference: Path) -> None:
    # The committed reference was independently generated by ngspice 46 and
    # represents the q-high stable branch of this intentionally multistable latch.
    expected_points = parse_listing(reference, "op")
    actual_points = parse_listing(listing, "op")
    require(sorted(expected_points) == [0], "reference must contain one OP point")
    require(sorted(actual_points) == [0], "listing must contain one OP point")

    expected = expected_points[0]
    actual = actual_points[0]
    require(set(actual) == set(expected), f"unexpected OP variables: {sorted(actual)}")
    for variable, expected_value in expected.items():
        actual_value = actual[variable]
        error = abs(actual_value - expected_value)
        require(
            math.isfinite(actual_value) and
            error <= ABSOLUTE_TOLERANCE[variable],
            f"{variable}: expected {expected_value:.12e}, "
            f"got {actual_value:.12e}, absolute error {error:.3e}",
        )


def main() -> int:
    arguments = parse_arguments()
    simulator = arguments.simulator.resolve()
    netlist = arguments.netlist.resolve()
    reference = arguments.reference.resolve()

    require(simulator.is_file(), f"simulator not found: {simulator}")
    require(netlist.is_file(), f"netlist not found: {netlist}")
    require(reference.is_file(), f"reference not found: {reference}")

    ordinary = run(simulator, "--pta", "disabled", netlist)
    require(
        ordinary.returncode == 1,
        f"ordinary OP unexpectedly returned {ordinary.returncode}: "
        f"{ordinary.stderr}{ordinary.stdout}",
    )
    require(
        "Operating point analysis failed" in ordinary.stderr,
        f"ordinary OP failure diagnostic is missing: {ordinary.stderr}",
    )
    require(not ordinary.stdout, "failed ordinary OP emitted a partial listing")

    with tempfile.TemporaryDirectory(prefix="pta-hard-op-") as directory:
        root = Path(directory)
        for mode in ("force", "fallback"):
            listing = root / f"{mode}.out"
            result = run(
                simulator,
                "--pta",
                mode,
                "--pta-diagnostics",
                *PTA_OPTIONS,
                "-o",
                listing,
                netlist,
            )
            require(
                result.returncode == 0,
                f"{mode} PTA failed ({result.returncode}): "
                f"{result.stderr}{result.stdout}",
            )
            require(not result.stdout, f"{mode} PTA ignored the listing output path")
            check_pta_diagnostics(result.stderr)
            check_operating_point(listing, reference)

    print("PASS PTA hard OP: ordinary path fails; force and fallback converge")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, ValueError) as error:
        print(f"FAIL PTA hard OP: {error}", file=sys.stderr)
        raise SystemExit(1)
